spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://10.12.188.112:3306/test
    url: jdbc:mysql:///test
    username: root
    password: ly666888
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 80
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml